### ISSUE TITLE
compiled app can't find audio file in working dir

### ISSUE THREAD

**Issue by AndrewPBerg** [AndrewPBerg/posture-productivity#50]
Traceback (most recent call last):
  File "main.py", line 276, in <module>
  File "main.py", line 253, in main
  File "gui_functions.py", line 48, in alert_user
pygame.error: No file 'buzz-notif.mp3' found in working directory 'C:\Users\Sidewinders\Desktop\compiled_app'.

Recompile with intent to include all posture-app dependencies

**Comment by AndrewPBerg** [comment]
[Suggested fix](https://stackoverflow.com/questions/57251491/is-pyinstaller-able-to-convert-py-file-to-exe-together-with-audio)

**Comment by AndrewPBerg** [comment]
did the add data in the main.spec file (un-commited local config file), then changed the `alert_user` code to help with file pathing issues
